using MacroDeck.Sdk.Variables;

namespace CsMd;

internal static class CsVariables
{
	private static readonly TimeSpan FastRefresh = TimeSpan.FromSeconds(1);
	private static readonly TimeSpan SlowRefresh = TimeSpan.FromSeconds(5);

	public static IReadOnlyList<VariableDefinition> CreateDefinitions() =>
	[
		Eager("gsi-connected", VariableType.Boolean, Strings.Variables.GsiConnected.DisplayName(), Strings.Variables.GsiConnected.Description(), refresh: TimeSpan.FromSeconds(2)),
		Eager("map-name", VariableType.Text, Strings.Variables.MapName.DisplayName(), Strings.Variables.MapName.Description(), refresh: SlowRefresh),
		Eager("map-mode", VariableType.Text, Strings.Variables.MapMode.DisplayName(), Strings.Variables.MapMode.Description(), refresh: SlowRefresh),
		Eager("map-phase", VariableType.Text, Strings.Variables.MapPhase.DisplayName(), Strings.Variables.MapPhase.Description(), refresh: FastRefresh),
		Eager("map-round", VariableType.Numeric, Strings.Variables.MapRound.DisplayName(), Strings.Variables.MapRound.Description(), refresh: FastRefresh),
		Eager("ct-score", VariableType.Numeric, Strings.Variables.CtScore.DisplayName(), Strings.Variables.CtScore.Description(), refresh: FastRefresh),
		Eager("t-score", VariableType.Numeric, Strings.Variables.TScore.DisplayName(), Strings.Variables.TScore.Description(), refresh: FastRefresh),
		Eager("ct-name", VariableType.Text, Strings.Variables.CtName.DisplayName(), Strings.Variables.CtName.Description(), refresh: SlowRefresh),
		Eager("t-name", VariableType.Text, Strings.Variables.TName.DisplayName(), Strings.Variables.TName.Description(), refresh: SlowRefresh),
		Eager("round-phase", VariableType.Text, Strings.Variables.RoundPhase.DisplayName(), Strings.Variables.RoundPhase.Description(), refresh: FastRefresh),
		Eager("bomb-state", VariableType.Text, Strings.Variables.BombState.DisplayName(), Strings.Variables.BombState.Description(), refresh: FastRefresh),
		Eager("phase-ends-in", VariableType.Numeric, Strings.Variables.PhaseEndsIn.DisplayName(), Strings.Variables.PhaseEndsIn.Description(), unit: "s", semanticKind: VariableSemanticKinds.Duration, refresh: FastRefresh),
		Eager("my-team", VariableType.Text, Strings.Variables.MyTeam.DisplayName(), Strings.Variables.MyTeam.Description(), refresh: SlowRefresh),
		Eager("player-name", VariableType.Text, Strings.Variables.PlayerName.DisplayName(), Strings.Variables.PlayerName.Description(), refresh: SlowRefresh),
		Eager("alive", VariableType.Boolean, Strings.Variables.Alive.DisplayName(), Strings.Variables.Alive.Description(), refresh: FastRefresh),
		Eager("health", VariableType.Numeric, Strings.Variables.Health.DisplayName(), Strings.Variables.Health.Description(), unit: "hp", refresh: FastRefresh),
		Eager("armor", VariableType.Numeric, Strings.Variables.Armor.DisplayName(), Strings.Variables.Armor.Description(), refresh: FastRefresh),
		Eager("helmet", VariableType.Boolean, Strings.Variables.Helmet.DisplayName(), Strings.Variables.Helmet.Description(), refresh: SlowRefresh),
		Eager("flashed", VariableType.Boolean, Strings.Variables.Flashed.DisplayName(), Strings.Variables.Flashed.Description(), refresh: FastRefresh),
		Eager("money", VariableType.Numeric, Strings.Variables.Money.DisplayName(), Strings.Variables.Money.Description(), unit: "$", refresh: FastRefresh),
		Eager("weapon", VariableType.Text, Strings.Variables.Weapon.DisplayName(), Strings.Variables.Weapon.Description(), refresh: FastRefresh),
		Eager("ammo-clip", VariableType.Numeric, Strings.Variables.AmmoClip.DisplayName(), Strings.Variables.AmmoClip.Description(), refresh: FastRefresh),
		Eager("ammo-reserve", VariableType.Numeric, Strings.Variables.AmmoReserve.DisplayName(), Strings.Variables.AmmoReserve.Description(), refresh: FastRefresh),
		Eager("kills", VariableType.Numeric, Strings.Variables.Kills.DisplayName(), Strings.Variables.Kills.Description(), refresh: SlowRefresh),
		Eager("deaths", VariableType.Numeric, Strings.Variables.Deaths.DisplayName(), Strings.Variables.Deaths.Description(), refresh: SlowRefresh),
		Eager("assists", VariableType.Numeric, Strings.Variables.Assists.DisplayName(), Strings.Variables.Assists.Description(), refresh: SlowRefresh),
		Eager("mvps", VariableType.Numeric, Strings.Variables.Mvps.DisplayName(), Strings.Variables.Mvps.Description(), refresh: SlowRefresh),
		Eager("score", VariableType.Numeric, Strings.Variables.Score.DisplayName(), Strings.Variables.Score.Description(), refresh: SlowRefresh),
		Eager("smokes-active", VariableType.Numeric, Strings.Variables.SmokesActive.DisplayName(), Strings.Variables.SmokesActive.Description(), refresh: FastRefresh),
		Eager("fire-active", VariableType.Numeric, Strings.Variables.FireActive.DisplayName(), Strings.Variables.FireActive.Description(), refresh: FastRefresh),
		Eager("pos-x", VariableType.Numeric, Strings.Variables.PosX.DisplayName(), Strings.Variables.PosX.Description(), refresh: FastRefresh),
		Eager("pos-y", VariableType.Numeric, Strings.Variables.PosY.DisplayName(), Strings.Variables.PosY.Description(), refresh: FastRefresh),
		Eager("pos-z", VariableType.Numeric, Strings.Variables.PosZ.DisplayName(), Strings.Variables.PosZ.Description(), refresh: FastRefresh),
		Eager("position-source", VariableType.Text, Strings.Variables.PositionSource.DisplayName(), Strings.Variables.PositionSource.Description(), refresh: TimeSpan.FromSeconds(2)),
		Eager("bomb-countdown", VariableType.Numeric, Strings.Variables.BombCountdown.DisplayName(), Strings.Variables.BombCountdown.Description(), unit: "s", semanticKind: VariableSemanticKinds.Duration, refresh: FastRefresh),
		Eager("bomb-carrier", VariableType.Text, Strings.Variables.BombCarrier.DisplayName(), Strings.Variables.BombCarrier.Description(), refresh: TimeSpan.FromSeconds(2)),
		Eager("place-name", VariableType.Text, Strings.Variables.PlaceName.DisplayName(), Strings.Variables.PlaceName.Description(), refresh: FastRefresh),
		Eager("session-kills", VariableType.Numeric, Strings.Variables.SessionKills.DisplayName(), Strings.Variables.SessionKills.Description(), refresh: FastRefresh),
		Eager("session-deaths", VariableType.Numeric, Strings.Variables.SessionDeaths.DisplayName(), Strings.Variables.SessionDeaths.Description(), refresh: FastRefresh),
		Eager("session-kd", VariableType.Numeric, Strings.Variables.SessionKd.DisplayName(), Strings.Variables.SessionKd.Description(), refresh: FastRefresh),
		Eager("round-kills", VariableType.Numeric, Strings.Variables.RoundKills.DisplayName(), Strings.Variables.RoundKills.Description(), refresh: FastRefresh),
		Eager("round-headshots", VariableType.Numeric, Strings.Variables.RoundHeadshots.DisplayName(), Strings.Variables.RoundHeadshots.Description(), refresh: FastRefresh),
		Eager("round-damage", VariableType.Numeric, Strings.Variables.RoundDamage.DisplayName(), Strings.Variables.RoundDamage.Description(), refresh: FastRefresh),
		Eager("smoked", VariableType.Boolean, Strings.Variables.Smoked.DisplayName(), Strings.Variables.Smoked.Description(), refresh: FastRefresh),
		Eager("burning", VariableType.Boolean, Strings.Variables.Burning.DisplayName(), Strings.Variables.Burning.Description(), refresh: FastRefresh),
		Eager("defusekit", VariableType.Boolean, Strings.Variables.Defusekit.DisplayName(), Strings.Variables.Defusekit.Description(), refresh: SlowRefresh),
		Eager("equip-value", VariableType.Numeric, Strings.Variables.EquipValue.DisplayName(), Strings.Variables.EquipValue.Description(), unit: "$", refresh: FastRefresh),
		Eager("player-activity", VariableType.Text, Strings.Variables.PlayerActivity.DisplayName(), Strings.Variables.PlayerActivity.Description(), refresh: SlowRefresh),
		Eager("player-clan", VariableType.Text, Strings.Variables.PlayerClan.DisplayName(), Strings.Variables.PlayerClan.Description(), refresh: SlowRefresh),
		Eager("weapon-type", VariableType.Text, Strings.Variables.WeaponType.DisplayName(), Strings.Variables.WeaponType.Description(), refresh: FastRefresh),
		Eager("round-history", VariableType.Text, Strings.Variables.RoundHistory.DisplayName(), Strings.Variables.RoundHistory.Description(), refresh: SlowRefresh),
		Eager("facing-yaw", VariableType.Numeric, Strings.Variables.FacingYaw.DisplayName(), Strings.Variables.FacingYaw.Description(), unit: "°", refresh: FastRefresh),
		Eager("grenades-active", VariableType.Numeric, Strings.Variables.GrenadesActive.DisplayName(), Strings.Variables.GrenadesActive.Description(), refresh: FastRefresh),
		Eager("ct-timeouts", VariableType.Numeric, Strings.Variables.CtTimeouts.DisplayName(), Strings.Variables.CtTimeouts.Description(), refresh: SlowRefresh),
		Eager("t-timeouts", VariableType.Numeric, Strings.Variables.TTimeouts.DisplayName(), Strings.Variables.TTimeouts.Description(), refresh: SlowRefresh),
		Eager("countdown-phase", VariableType.Text, Strings.Variables.CountdownPhase.DisplayName(), Strings.Variables.CountdownPhase.Description(), refresh: FastRefresh),
		Eager("kill-streak", VariableType.Numeric, Strings.Variables.KillStreak.DisplayName(), Strings.Variables.KillStreak.Description(), refresh: FastRefresh),
		Eager("best-streak", VariableType.Numeric, Strings.Variables.BestStreak.DisplayName(), Strings.Variables.BestStreak.Description(), refresh: FastRefresh),
		Eager("top-weapon", VariableType.Text, Strings.Variables.TopWeapon.DisplayName(), Strings.Variables.TopWeapon.Description(), refresh: FastRefresh),
		Eager("top-weapon-kills", VariableType.Numeric, Strings.Variables.TopWeaponKills.DisplayName(), Strings.Variables.TopWeaponKills.Description(), refresh: FastRefresh),
		Eager("rounds-played", VariableType.Numeric, Strings.Variables.RoundsPlayed.DisplayName(), Strings.Variables.RoundsPlayed.Description(), refresh: SlowRefresh),
		Eager("session-damage", VariableType.Numeric, Strings.Variables.SessionDamage.DisplayName(), Strings.Variables.SessionDamage.Description(), refresh: FastRefresh),
		Eager("loss-bonus", VariableType.Numeric, Strings.Variables.LossBonus.DisplayName(), Strings.Variables.LossBonus.Description(), unit: "$", refresh: SlowRefresh),
		Eager("session-adr", VariableType.Numeric, Strings.Variables.SessionAdr.DisplayName(), Strings.Variables.SessionAdr.Description(), refresh: FastRefresh),
		Eager("session-hs", VariableType.Numeric, Strings.Variables.SessionHs.DisplayName(), Strings.Variables.SessionHs.Description(), refresh: FastRefresh),
		Eager("hs-rate", VariableType.Numeric, Strings.Variables.HsRate.DisplayName(), Strings.Variables.HsRate.Description(), refresh: FastRefresh),
		Eager("match-elapsed", VariableType.Numeric, Strings.Variables.MatchElapsed.DisplayName(), Strings.Variables.MatchElapsed.Description(), unit: "s", semanticKind: VariableSemanticKinds.Duration, refresh: FastRefresh),
		Eager("session-match-time", VariableType.Numeric, Strings.Variables.SessionMatchTime.DisplayName(), Strings.Variables.SessionMatchTime.Description(), unit: "s", semanticKind: VariableSemanticKinds.Duration, refresh: SlowRefresh),
		Eager("last-chat", VariableType.Text, Strings.Variables.LastChat.DisplayName(), Strings.Variables.LastChat.Description(), refresh: TimeSpan.FromSeconds(2)),
	];

	private static VariableDefinition Eager(
		string id,
		VariableType type,
		MacroDeck.Localization.LocalizedText displayName,
		MacroDeck.Localization.LocalizedText description,
		string? unit = null,
		string? semanticKind = null,
		TimeSpan? refresh = null) =>
		VariableDefinition.Eager(id, type) with
		{
			Name = id.Replace("-", "_"),
			DisplayName = displayName,
			Description = description,
			Unit = unit ?? string.Empty,
			SemanticKind = semanticKind ?? VariableSemanticKinds.None,
			RefreshInterval = refresh,
		};
}
